# Generated by Django 3.1.3 on 2020-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201031_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('BOOKS', 'Books'), ('BEAUTY', 'Beauty'), ('CLOTH', 'Clothing'), ('MUSIC', 'Musical Instruments')], default='GEN', max_length=100),
        ),
    ]
