# Generated by Django 3.1.3 on 2020-11-17 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2003, 8, 30, 0, 0)),
        ),
    ]
